#####################################
# Local Development
#####################################
version: "3.8"

########################### SERVICES
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - wordpress:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        ## HTTP Routers
        - traefik.http.routers.test_hyeon.entrypoints=websecure
        - traefik.http.routers.test_hyeon.rule=Host(`test.nas.hyeon.pro`)
        - traefik.http.routers.test_hyeon.tls.certresolver=leresolver
        - traefik.http.services.test_hyeon.loadbalancer.server.port=80
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-redis:v1.0.0
    environment:
      WORDPRESS_DB_HOST: DB_mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_REDIS_HOST: DB_redis
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - wordpress:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=false

########################### NETWORKS
networks:
  default:
    external:
      name: DB_net
volumes:
  wordpress:
